#pragma once
#include "../xrECore/stdafx.h"
#include "../xrECore/Editor/device.h"
#include "../xrECore/Editor/UI_MainCommand.h"
#include "../xrECore/Editor/UI_ToolsCustom.h"
#include "../xrECore/Editor/ui_main.h"
#include "../xrECore/Editor/GeometryCollector.h"
#include "../xrECore/Editor/EditorPreferences.h"
#include "../xrECore/Editor/render.h"
#include "../xrECore/Editor/UIRenderForm.h"
#include "../xrECore/Editor/ELog.h"
#include "../xrECore/Editor/tlsprite.h"
#include "../xrECore/Editor/EditObject.h"
#include "../xrECore/Editor/EditMesh.h"
#include "../xrECore/Editor/D3DUtils.h"
#include "../xrEcore/Editor/PhysicsShellHolderEditorBase.h"
#include "../xrETools/ETools.h"
#include "../xrECore/Engine/Texture.h"
#include "../xrECore/Editor/Library.h"
#include "../xrECore/Editor/ImageManager.h"
#include "../xrECore/Editor/pick_defs.h"
#include "../xrECore/Editor/SoundManager.h"
#include "../xrECore/Editor/EDetailModel.h"
#include "../xrECore/Engine/Image.h"
#include "../xrECore/Engine/guid_generator.h"
#include "../xrECore/Editor/ExportSkeleton.h"
#include "../FreeMagic/MgcAppr3DPlaneFit.h"
#include "../FreeMagic/MgcEigen.h"
#include "../FreeMagic/MgcLinearSystem.h"
#include "../FreeMagic/MgcConvexHull2D.h"

#include "../xrCore/doug_lea_allocator.h"
#include "../xrCore/FixedMap.h"

#include "LightAnimLibrary.h"
#include "motion.h"
#include "envelope.h"
#include "communicate.h"
#include "xrHemisphere.h"
#include "LevelGameDef.h"
#include "SkeletonAnimated.h"
#include "ObjectAnimator.h"
#include "xr_efflensflare.h"
#include "du_box.h"
#include "Communicate.h"
#include "pure.h"
#include "xrLevel.h"
#include "xrEditorSceneInterface.h"
#include "std_classes.h"
#include "IGame_Persistent.h"
#include "XR_IOConsole.h"
#include "CustomHUD.h"
#include "CameraManager.h"
#include "IGame_Level.h"
#include "x_ray.h"
#include "..\..\xrCDB\xrCDB.h"
#include "..\..\xrCDB\ISpatial.h"
#include "..\..\xrRender\Public\ParticleCustom.h"
#include "..\..\xrRender\Private\DetailManager.h"
#include "..\..\xrRender\Private\ParticleEffect.h"
#include "..\..\xrRender\Private\ParticleEffectDef.h"
#include "..\..\xrRender\Private\ParticleGroup.h"
#include "EngineAPI.h"
#include "cl_intersect.h"

#include "../../xrServerEntities/xrMessages.h"

#ifndef _DEBUG
#define USE_ARENA_ALLOCATOR
#endif

#include "AI/game_graph_builder.h"
#include "AI/level_graph_editor.h"

#include "Engine/XRayEditor.h"
#include "Engine/xrGameManager.h"

#include "UI/UITopBarForm.h"
#include "UI/UIMainMenuForm.h"
#include "UI/UILeftBarForm.h"
#include "UI/UILPropertiesFrom.h"
#include "UI/UIMainForm.h"
#include "UI/Tools/UIToolCustom.h"
#include "UI/UIPropertiesModal.h"
#include "UI/Tools/UIShapeTool.h"

#include "Editor/Tools/ESceneClassList.h"

#include "Editor/Utils/Gizmo/IM_Manipulator.h"

#include "Editor/UI_LevelMain.h"
#include "Editor/UI_LevelTools.h"

#include "Editor/Utils/portalutils.h"
#include "Editor/Utils/xrSEFactoryManager.h"
#include "Editor/Utils/iniStreamImpl.h"
#include "Editor/Utils/SoundManager_LE.h"
#include "Editor/Utils/LevelPreferences.h"
#include "Editor/Utils/Custom2DProjector.h"

#include "Editor/Entry/CustomObject.h"
#include "Editor/Entry/Glow/glow.h"
#include "Editor/Entry/Group/GroupObject.h"
#include "Editor/Entry/Light/ELight.h"
#include "Editor/Entry/Particles/EParticlesObject.h"
#include "Editor/Entry/Portal/portal.h"
#include "Editor/Entry/Sector/sector.h"
#include "Editor/Entry/Shape/EShape.h"
#include "Editor/Entry/Sound/ESound_Environment.h"
#include "Editor/Entry/Sound/ESound_Source.h"
#include "Editor/Entry/Spawn/SpawnPoint.h"
#include "Editor/Entry/StaticObject/SceneObject.h"
#include "Editor/Entry/WayPoint/WayPoint.h"

#include "Editor/Tools/Base/ESceneControlsCustom.h"
#include "Editor/Tools/Base/ESceneCustomMTools.h"
#include "Editor/Tools/Base/ESceneCustomOTools.h"
#include "Editor/Tools/Base/ESceneDummyTools.h"

#include "Editor/Tools/AIMap/ESceneAIMapTools_Export.h"
#include "Editor/Tools/AIMap/ESceneAIMapTools.h"
#include "Editor/Tools/AIMap/ESceneAIMapControls.h"
#include "Editor/Tools/Details/ESceneDOTools.h"
#include "Editor/Tools/FogVolume/ESceneFogVolumeTools.h"
#include "Editor/Tools/Group/ESceneGroupTools.h"
#include "Editor/Tools/Group/ESceneGroupControls.h"
#include "Editor/Tools/Light/ESceneLightTools.h"
#include "Editor/Tools/Particles/EScenePSTools.h"
#include "Editor/Tools/Particles/EScenePSControls.h"
#include "Editor/Tools/Sector/ESceneSectorTools.h"
#include "Editor/Tools/Sector/ESceneSectorControls.h"
#include "Editor/Tools/Portal/EScenePortalTools.h"
#include "Editor/Tools/Portal/EScenePortalControls.h"
#include "Editor/Tools/Shape/ESceneShapeTools.h"
#include "Editor/Tools/Shape/ESceneShapeControls.h"
#include "Editor/Tools/Sound/ESceneSoundSrcTools.h"
#include "Editor/Tools/Sound/ESceneSoundEnvTools.h"
#include "Editor/Tools/Spawn/ESceneSpawnTools.h"
#include "Editor/Tools/Spawn/ESceneSpawnControls.h"
#include "Editor/Tools/StaticObject/ESceneObjectTools.h"
#include "Editor/Tools/StaticObject/ESceneObjectControls.h"
#include "Editor/Tools/Wallmark/ESceneWallmarkTools.h"
#include "Editor/Tools/Wallmark/ESceneWallmarkControls.h"
#include "Editor/Tools/WayPoint/ESceneWayTools.h"
#include "Editor/Tools/WayPoint/ESceneWayControls.h"
#include "Editor/Tools/Glow/ESceneGlowTools.h"

#include "Editor/Scene/CFromBuilder.h"
#include "Editor/Scene/scene.h"
#include "Editor/Scene/SceneGraph.h"
#include "Editor/Scene/SceneSummaryInfo.h"
#include "Editor/Builder/Builder.h"

#include "Editor/Utils/xrSEFactoryManager.h"

#include "UI/UIMainForm.h"
#include "UI/UIMainMenuForm.h"
#include "UI/UIDOOneColor.h"
#include "UI/UIDOShuffle.h"
#include "UI/UILeftBarForm.h"
#include "UI/UILPropertiesFrom.h"
#include "UI/UIWorldPropertiesFrom.h"
#include "UI/ObjectList/UIObjectListItem.h"
#include "UI/ObjectList/UIObjectList.h"
#include "UI/UIPropertiesModal.h"
#include "UI/UITopBarForm.h"

#include "UI/Tools/UIAIMapTool.h"
#include "UI/Tools/UIDOTool.h"
#include "UI/Tools/UIFogVolTool.h"
#include "UI/Tools/UIGroupTool.h"
#include "UI/Tools/UILightTool.h"
#include "UI/Tools/UIObjectTool.h"
#include "UI/Tools/UIParticlesTool.h"
#include "UI/Tools/UIPortalTool.h"
#include "UI/Tools/UISectorTool.h"
#include "UI/Tools/UIShapeTool.h"
#include "UI/Tools/UISpawnTool.h"
#include "UI/Tools/UIToolCustom.h"
#include "UI/Tools/UIWayTool.h"
